import {
    Loader2,
    Github,
    Mail,
    User,
    Settings,
    LogOut,
    Plus,
    Search,
    Check,
    ChevronRight,
    ChevronLeft,
    MoreHorizontal,
    Trash,
    Code2,
    LayoutDashboard,
    Moon,
    Sun,
    Laptop,
    Heart,
    Link as LinkIcon,
    Twitter,
    Folder,
    Star,
    Filter,
    Bell,
    Trophy,
    Eye,
    MessageSquare,
    Send,
} from "lucide-react"

export const Icons = {
    spinner: Loader2,
    gitHub: Github,
    mail: Mail,
    user: User,
    settings: Settings,
    logout: LogOut,
    add: Plus,
    search: Search,
    check: Check,
    chevronRight: ChevronRight,
    chevronLeft: ChevronLeft,
    ellipsis: MoreHorizontal,
    trash: Trash,
    code: Code2,
    dashboard: LayoutDashboard,
    moon: Moon,
    sun: Sun,
    laptop: Laptop,
    heart: Heart,
    link: LinkIcon,
    twitter: Twitter,
    folder: Folder,
    star: Star,
    filter: Filter,
    bell: Bell,
    trophy: Trophy,
    eye: Eye,
    message: MessageSquare,
    send: Send,
}
